apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-app
spec:
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      containers:
        - name : django-container
          image: django_image:latest
          env:
          - name: DATABASE_URL
            value: postgres://admin:123321@192.168.88.233:5544/mydb
          - name: SECRET_KEY
            value: secret-key
          - name: DEBUG
            value: "True"
          - name: ALLOWED_HOSTS
            value: "*"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    project: django
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer