apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsession
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      startingDeadlineSeconds: 3500
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: django-container
              image: django_image
              command: ['python', 'manage.py', 'clearsessions']
              imagePullPolicy: Never
              envFrom:
              - configMapRef:
                  name: dj-conf
          restartPolicy: OnFailure